language: c

services:
  - docker

before_install:
  - docker build -t lua/louis .

script:
  - docker run lua/louis /bin/sh -c "eval `luarocks path` && lua -e \"print(require'liblua-louis'.translateString('en-ueb-g2.ctb', 'Hello World'))\""

branches:
  only:
    - master

script:
  - lua -e "print(require'liblua-louis'.translateString('en-ueb-g2.ctb', 'Hello World'))"

notifications:
   irc: "irc.oftc.net#liblouis"
