language: c

sudo: false

env:
  global:
    - LUAROCKS=3.3.1
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3

branches:
  only:
    - master

before_install:
  - source .travis/setenv_lua.sh
  - sudo apt-get update -qq
  - sudo apt -y install liblouis-dev liblouis-data


install:
  - ./autogen.sh
  - luarocks make rockspecs/lua-louis-scm-0.rockspec

script:
  - lua -e "print(require'liblua-louis'.translateString('en-ueb-g2.ctb', 'Hello World'))"

notifications:
   irc: "irc.oftc.net#liblouis"
